wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/train_classifier.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batchsize:
  desc: null
  value: 512
checkpoint_freq:
  desc: null
  value: 1
comment:
  desc: null
  value: null
config:
  desc: null
  value: configs/iic/mnist.yaml
data_aug_max_rotate:
  desc: null
  value: 0.3
data_aug_tps_cntl_pts:
  desc: null
  value: 4
data_aug_tps_variance:
  desc: null
  value: 0.11
data_aug_type:
  desc: null
  value: tps_and_rotate
dataroot:
  desc: null
  value: data
dataset_name:
  desc: null
  value: mnist_no_trans
dataset_randomize:
  desc: null
  value: null
dataset_test_len:
  desc: null
  value: null
dataset_train_len:
  desc: null
  value: null
demo:
  desc: null
  value: false
device:
  desc: null
  value: cuda:0
display:
  desc: null
  value: 10
display_freq:
  desc: null
  value: 5000
display_kp_rows:
  desc: null
  value: 4
epochs:
  desc: null
  value: 200
export:
  desc: null
  value: null
load:
  desc: null
  value: null
model_encoder:
  desc: null
  value:
  - 1
  - 64
  - 64
  - 128
  - 128
  - M
  - 256
  - 256
  - 256
  - M
  - 512
  - 512
  - 512
  - M
  - 512
  - 512
  - 512
  - M
model_init:
  desc: null
  value: xavier_normal
model_name:
  desc: null
  value: VGG16
model_type:
  desc: null
  value: vgg16
name:
  desc: null
  value: null
opt_level:
  desc: null
  value: O0
optim_class:
  desc: null
  value: Adam
optim_lr:
  desc: null
  value: 0.0001
optlevel:
  desc: null
  value: null
processes:
  desc: null
  value: null
run_id:
  desc: null
  value: 21
scheduler_class:
  desc: null
  value: null
seed:
  desc: null
  value: null
transfer_load:
  desc: null
  value: null
